title: Software development, productivity, life wellbeing, reading stuff.
description: Blog for me to dump all the things that i learn recently
author: Qaiyyum Hakimi
github: https://github.com/qhkm92
about: Fullstack developer for a internet marketing company in Tokyo.
I've made quite a few web apps, especially in react, typescript, node.
Now i'm learning golang and backend as a whole, to improve my skills.
If you are interested to collaborate more, feel free to contact me!
disqus_shortname: blogging
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://qhkm92.github.io/"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: https://qhkm92.github.io/blog
baseurl: /blog
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

sass:
  style: compact
  sass_dir: _sass